name: Parse JSON from Issue Comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  convert:
    if: github.event.issue.title == 'Roster Inbox'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Write comment to latest.json
        run: |
          echo "${{ github.event.comment.body }}" > data/rosters/latest.json
      - name: Write comment to dated file
        run: |
          COMMENT_TIME="${{ github.event.comment.created_at }}"
          offset=$(date -d "$COMMENT_TIME" +%w)
          sunday=$(date -d "$COMMENT_TIME - $offset days" +%F)
          mkdir -p data/rosters
          printf '%s\n' "${{ github.event.comment.body }}" > "data/rosters/${sunday}.json"
          cp "data/rosters/${sunday}.json" data/rosters/latest.json
      - name: Commit and push
        run: |
          git config user.name  roster-bot
          git config user.email bot@example.com
          git add data/rosters/*.json
          git diff --cached --quiet || git commit -m "Update roster from comment"
          git push
